version: '3.9'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env.docker
    ports:
      - '5432:5432'