version: '3.3'

services:
  db:
    restart: always
    container_name: db
    env_file:
      - ./.env
    image: postgres:14.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.env.docker
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/cache:/data

  celery:
    container_name: celery
    build: .
    command: >
      bash -c "celery -A config.celery worker --loglevel=info"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - db
      - api

  celery-beat:
    container_name: celery-beat
    build: .
    command: >
      bash -c "sleep 30 && celery -A config.celery beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - api
      - celery

volumes:
  postgres_data: