# Generated by Django 4.2.3 on 2023-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_image/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Lessons_image/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
                'ordering': ('title',),
            },
        ),
    ]
