# Generated by Django 4.2.3 on 2023-07-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_remove_course_lessons_lessons_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ('course',), 'verbose_name': 'лекция', 'verbose_name_plural': 'лекции'},
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='стоимость курса'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата оплаты')),
                ('payment_method', models.CharField(choices=[('CARD', 'перевод на счет'), ('CASH', 'наличными средствами')], max_length=100, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course', verbose_name='название курса')),
                ('price', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='school.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
