# Generated by Django 4.2.3 on 2023-07-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_lessons_options_course_price_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='school.course', verbose_name='стоимость курса'),
        ),
    ]
