# Generated by Django 4.2.3 on 2023-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_payment_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('price',), 'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0, verbose_name='стоимость курса'),
        ),
    ]
