# Generated by Django 4.2.3 on 2023-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_subscribetocourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribetocourse',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='subscribetocourse',
            name='subscribe_status',
            field=models.CharField(choices=[('TRUE', 'Вы подписаны'), ('FALSE', 'Вы не подписаны')], default='Вы не подписаны', max_length=100, verbose_name='статус подписки'),
        ),
    ]
