# Generated by Django 4.2.3 on 2023-08-04 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0012_alter_subscribetocourse_subscribe_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribeToCourse',
            new_name='Subscribe',
        ),
    ]
