# Generated by Django 4.2.3 on 2023-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_rename_subscribetocourse_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_status',
            field=models.BooleanField(default=False, verbose_name='статус подписки'),
        ),
    ]
