# Generated by Django 4.2.3 on 2023-08-04 22:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0015_alter_subscribe_subscribe_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('owner', 'course')},
        ),
    ]
