# Generated by Django 4.2.3 on 2023-08-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_rename_user_subscribe_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=set(),
        ),
    ]
